function check_accuracy(subjectID)
%% change .pro to .txt %%%%%%%%%%%%%%%%%
pro_file = dir('*.pro');
if ~isempty(pro_file)
for file_iter = 1:height(pro_file)
    namePRO = pro_file(file_iter).name;
    nameTXT = [namePRO(1:end-3), 'txt'];
    copyfile(namePRO,nameTXT)
end
end
% filenames
filename_pro = ['Kappa3Tone1_prac_',subjectID,'_protocol.txt'];
filename_log = ['Kappa3Tone1_prac_',subjectID,'_log.txt'];

% experiment parameters
rows_per_block_pro = 10;
trials_per_block = 20;
shortlong_button = 1;
longshort_button = 2;
accuracy_threshold = 0.8;

%% read file
pro_data = importfile(filename_pro);
% response
response = str2num(char(table2array(pro_data(7:rows_per_block_pro:height(pro_data),'StandardProtocolFileGeneratedByMatlabAfcProcedure'))))';

%% load log file
log_data = char(importdata(filename_log));
trial_num = height(log_data);
for trial_iter = 1:trial_num
%     temp_strs = strsplit(char(log_data(trial_iter,:)),',');
    log_data(trial_iter,:) = strrep(log_data(trial_iter,:),'prac','0   ');
end
log_data = str2num(log_data);
%% separate blocks
block_num = height(log_data)/trials_per_block;
timeoffset = [];
for block_iter = 1:block_num
% time shift of target tone from midpoint (in ms)
timeoffset = [timeoffset,log_data(trials_per_block*(block_iter-1)+1:trials_per_block*block_iter,1)];
end
% correct response
correctresp = timeoffset;
correctresp(correctresp>0) = longshort_button;
correctresp(correctresp<0) = shortlong_button;

%% check response
correct_trial = response == correctresp;
accuracy = sum(correct_trial,1)/trials_per_block;
disp(accuracy)
if accuracy(end)>=accuracy_threshold
    disp('continue experiment')
else
    disp('redo practice')
end
end

function Kappa3Tone1vel6protocol = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  KAPPA3TONE1VEL6PROTOCOL = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  KAPPA3TONE1VEL6PROTOCOL = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Kappa3Tone1vel6protocol = importfile("/Users/yinzhiqing/Documents/mehta lab/with carrie/example files/20230321/Kappa3Tone1_vel6_protocol.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Apr-2023 15:41:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "StandardProtocolFileGeneratedByMatlabAfcProcedure";
opts.VariableTypes = "categorical";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "StandardProtocolFileGeneratedByMatlabAfcProcedure", "EmptyFieldRule", "auto");

% Import the data
Kappa3Tone1vel6protocol = readtable(filename, opts);

end